app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='users')),
]


admin.site.site_header = "Панель администратора"
admin.site.site_title = "Администрирование"
admin.site.index_title = ""

# if settings.DEBUG:
#     urlpatterns += [
#     path("__debug__/", include("debug_toolbar.urls")),
# ]

# if settings.DEBUG:
#         urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)    

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    # image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Аватар')
    phone_number = models.CharField(max_length=10, blank=True, null=True, verbose_name='Номер телефона')
    birth_date = models.CharField(max_length=10, blank=True, null=True, verbose_name='Дата рождения')
    first_name = models.CharField(max_length=150, blank=True, verbose_name='Имя')
    last_name = models.CharField(max_length=150, blank=True, verbose_name='Фамилия')
    surname = models.CharField(max_length=10, blank=True, null=True, verbose_name='Отчество')
    username = models.CharField(
        ("пользователь"),
        max_length=150,
        unique=True,
        validators=[AbstractUser.username_validator],
        error_messages={
            "unique": ("A user with that username already exists."),
        },
    )

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['username', 'password']

    username = forms.CharField()
    password = forms.CharField()


class UserRegistrationForm(UserCreationForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

users/views.py
from django.contrib import messages, auth
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from users.forms import UserLoginForm, UserRegistrationForm

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = request.session.session_key

            if user:
                auth.login(request, user)
                # messages.success(request, f"{username}, Вы вошли в аккаунт!")

                if request.POST.get('next', None):
                    return HttpResponseRedirect(request.POST.get('next'))

                return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'DMShop - Авторизация',
        'form': form,

    }
    return render(request, 'users/login.html', context)

def register(request):

    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()

            session_key = request.session.session_key

            user = form.instance
            auth.login(request, user)

            # messages.success(request, f"{user.username}, Вы успешно зарегистрированы!")
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'DMShop - Регистрация',
        'form': form,
    }
    return render(request, 'users/register.html', context)

@login_required
def logout(request):
    auth.logout(request)
    # messages.success(request, f"{request.user.username}, Вы вышли из аккаунта!")
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% extends "base.html" %}
{% load static %}



{% block section %}

    <section class="ftco-section contact-section ftco-no-pb" id="login" >
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
        <div class="col-md-7 heading-section text-center ftco-animate">
          <h2 class="mb-4">Авторизация</h2>
        </div>
      </div>

      <div class="row no-gutters block-9" style="width: 100%;margin:auto;padding-bottom:50px;"> 

        
          <form action="{% url "users:login" %}" method="post" id="myForm" class="bg-light p-4 p-md-5 contact-form">
            {% csrf_token %}

            {% if request.GET.next %}
              <input type="hidden" name="next" value={{request.GET.next}} >
            {% endif %}

            <div class="form-group">
              <label for="id_username" class="form-label">Имя пользователя</label>
              <input type="text" id="id_username" class="form-control" name="username" value="{% if form.username.value %} {{ form.username.value }} {% endif %}" placeholder="Введите имя пользователя">
            </div> 

            <div class="form-group">
              <label for="id_password" class="form-label">Пароль</label>
              <input type="password" name="password" id="id_password" class="form-control" placeholder="Введите пароль" value="{% if form.password.value %} {{ form.password.value }} {% endif %}">
            </div> 
            
            <p>
              <div class="form-group">
                  <input type="submit" id="submitButton" value="Войти" class="btn btn-primary py-3 px-5" style="margin:auto;">
              </div>
            </p> 

            <p>
                <div class="form-group">
                    Нет аккаунта? | <a href="{% url "users:register" %}" style="text-decoration: none;">Зарегистрироваться</a>
                </div>
            </p>
            
          
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    const form = document.getElementById('myForm');
                    const submitButton = document.getElementById('submitButton');
                    const inputs = form.querySelectorAll('input'); // Выбираем все поля ввода
            
                    // Функция для проверки заполненности всех полей
                    function checkForm() {
                        let allFilled = true;
                        inputs.forEach(input => {
                            if (!input.value.trim()) { // Проверяем, заполнено ли поле
                                allFilled = false;
                            }
                        });
                        submitButton.disabled = !allFilled; // Делаем кнопку активной/неактивной
                    }
            
                    // Добавляем обработчик события 'input' на каждое поле
                    inputs.forEach(input => {
                        input.addEventListener('input', checkForm);
                    });
            
                    // Проверяем форму при загрузке страницы
                    checkForm();
                });
            </script>

          </form>
        



      </div>

    </div>
  </section>

{% endblock section %}

users/templates/users/register.html
{% extends "base.html" %}
{% load static %}

{% block section %}
<section class="ftco-section contact-section ftco-no-pb" id="login">
    <div class="container">
        <div class="row justify-content-center mb-5 pb-3">
        <div class="col-md-7 heading-section text-center ftco-animate">
          <h2 class="mb-4">Регистрация</h2>
        </div>
      </div>

      <div class="row no-gutters block-9" style="width: 100%;margin:auto;padding-bottom:50px;">
          <form method="post" action="{% url "users:register" %}" id="myForm" class="bg-light p-4 p-md-5 contact-form">
            {% csrf_token %}

            <div class="form-group">
                <label for="id_first_name" class="form-label">Имя*</label>
                <input type="text" class="form-control" id="id_first_name"
                      value="{% if form.first_name.value %} {{ form.first_name.value }} {% endif %}"
                      name="first_name"
                    placeholder="Введите ваше имя" required>
                    {% if form.first_name.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                    {% endif %}
            </div>

            <div class="form-group">
                <label for="id_last_name" class="form-label">Фамилия*</label>
                <input type="text" class="form-control" id="id_last_name"
                      value="{% if form.last_name.value %} {{ form.last_name.value }} {% endif %}"
                      name="last_name"
                    placeholder="Введите вашу фамилию" required>
                    {% if form.last_name.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                    {% endif %}
            </div>

            <div class="form-group">
                <label for="id_username" class="form-label">Имя пользователя*</label>
                <input type="text" class="form-control" id="id_username"
                      value="{% if form.username.value %} {{ form.username.value }} {% endif %}"
                      name="username"
                    placeholder="Введите имя пользователя" required>
                    {% if form.username.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                    {% endif %}
            </div>

            <div class="form-group">
                <label for="id_email" class="form-label">Email*</label>
                <input type="email" class="form-control" id="id_email"
                      value="{% if form.email.value %} {{ form.email.value }} {% endif %}"
                      name="email"
                    placeholder="Введите ваш email" required>
                    {% if form.email.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                    {% endif %}
            </div>

            <div class="form-group">
                <label for="id_password1" class="form-label">Пароль*</label>
                <input type="password" class="form-control" id="id_password1"
                      value="{% if form.password1.value %} {{ form.password1.value }} {% endif %}"
                      name="password1"
                    placeholder="Введите пароль" required>
                    {% if form.password1.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                    {% endif %}
            </div>

            <div class="form-group">
                <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                <input type="password" class="form-control" id="id_password2"
                      value="{% if form.password2.value %} {{ form.password2.value }} {% endif %}"
                      name="password2"
                    placeholder="Подтвердите пароль" required>
                    {% if form.password2.errors %}
                        <div class="alert alert-danger alert-dismissible fade show">
                            {{form.password2.errors}}</div>
                    {% endif %}
            </div>

            <div class="form-check">
              <input class="form-check-input" type="checkbox" id="flexCheckDefault">
              <label class="form-check-label" for="flexCheckDefault">
                Согласие на обработку персональных данных
              </label>
            </div>
            
            <p>
              <div class="form-group">
                  <input type="submit" id="submitButton" value="Зарегистрироваться" disabled class="btn btn-primary py-3 px-5" style="margin:auto">
              </div>
            </p> 

          </form>
      </div>

    </div>
  </section>
{% endblock section %}
{% block js %}
  <script>
    document.addEventListener('DOMContentLoaded', function() {
        const checkbox = document.getElementById('flexCheckDefault');
        const submitButton = document.getElementById('submitButton');

        // Проверяем состояние чекбокса при изменении
        checkbox.addEventListener('change', function() {
            submitButton.disabled = !checkbox.checked;
        });
    });
  </script>
{% endblock js %}