app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='users')),
]


admin.site.site_header = "Панель администратора"
admin.site.site_title = "Администрирование"
admin.site.index_title = ""

# if settings.DEBUG:
#     urlpatterns += [
#     path("__debug__/", include("debug_toolbar.urls")),
# ]

# if settings.DEBUG:
#         urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)    

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('toggle_theme/', views.toggle_theme, name='toggle_theme'),
    path('curse/<slug:curse_slug>/', views.curse_cart, name='curse_cart'),
    path('students/', views.students, name='students'),
    path('get_file/', views.export_to_csv, name='get_file'),
    path('news/<slug:news_slug>', views.news, name='news'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

	{% load static %}

	<head>
		<title>{{ title }}</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Unbounded:wght@200..900&display=swap" rel="stylesheet">

		<link rel="stylesheet" href="{% static 'css/animate.css' %}">

		<link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
		<link rel="stylesheet" href="{% static 'css/aos.css' %}">
		<link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}">
		<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
		<link rel="stylesheet" href="{% static 'css/icomoon.css' %}">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">

		<link rel="icon" href="{% static 'images/favicon.ico' %}">

		<script src="https://cdnjs.cloudflare.com/ajax/libs/animejs/3.2.1/anime.min.js"></script>


		{% block css %}
		{% endblock css %}
		
		{% if request.session.theme == 'light' %}
			{% comment %} Блок для изменения темы {% endcomment %}
				<style>
					body {
						background: white;
						color: #565656
					}

					.ftco-footer a:hover {
						color: #ffbd39
					}

					.ftco-footer-social li a:hover {
						color: black
					}

					.slider-text .bread {
						color: black;
					}

					.slider-text .breadcrumbs span a {
						color: grey !important;
					}

					.slider-text .breadcrumbs span {
						color: grey !important;
					}

					.bg-dark {
						background: #e9e9e9 !important;
					}

					.block-21 .text .heading a {
						color:black;
					}

					.ftco-counter .block-18 {
						background: #f1e9e9;
					}

					.ftco-counter .text span {
						color: grey;
					}

					.ftco-navbar-light .navbar-nav > .nav-item > .nav-link {
						color: black !important;
					}

					.blog-entry .text .heading a {
						color: black;
					}

					.ftco-navbar-light .navbar-brand {
						color: black;
					}

					.ftco-navbar-light {
						background: white !important;
						border-bottom: 2px solid black;
					}


				
					.ftco-navbar-light.scrolled .navbar-brand {
						color: black !important;
					}


					.ftco-navbar-light.scrolled .nav-item > .nav-link {
						color: black;
					}

					.ftco-navbar-light.scrolled {
						background: white !important;
						border-bottom: 2px solid black;
					}

					.ftco-footer {
						background: white;
					}

					.ftco-footer .ftco-footer-widget h2 {
						color: black;
					}

					.ftco-footer a {
						color: grey;
					}

					.ftco-footer p {
						color: grey;
					}

					.project .text h3 a {
						color: black;
					}

					.project .text span {
						color: black;
					}

					h1, h2, h3, h4, h5, .h1, .h2, .h3, .h4, .h5 {
						color: black;
					}


					.bg-light {
						background: #f1e9e9 !important;
					} 

					{% comment %} .form-control {
						background: black !important;
					} {% endcomment %}

				</style>
			{% comment %}{% endcomment %}
		{% endif %}

	</head>

	<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
		
		{% comment %} Верхнее меню {% endcomment %}
		<nav class="navbar navbar-expand-lg navbar-dark ftco_navbar ftco-navbar-light site-navbar-target" id="ftco-navbar" style="{% if request.session.theme != 'light' %}border-bottom: 2px solid white;{% endif %}">
			<div class="container">

				<div class="nav-link"> 
					{% comment %} <a class="navbar-brand">ПФЭК ДПО</a> {% endcomment %}
					 <a href="{% url "main:index" %}">
						<img src="{% if request.session.theme != 'dark' %}{% static 'images/logo_fu.png' %}{% else %}{% static 'images/logo_fu-invert.png' %}{% endif %}" width="240px" height="80px">
					 </a>
				</div>

				<button class="navbar-toggler js-fh5co-nav-toggle fh5co-nav-toggle" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
					<div class="navbar-brand" style="padding-bottom:15px"><span class="oi oi-menu"></span></div>
				</button>

				<div class="collapse navbar-collapse" style="padding-left: 20px;" id="ftco-nav">
					
					<ul class="navbar-nav nav ml-auto">
						<li class="nav-item"><a href="{% if request.path != "/" %}{% url "main:index" %}{% else %}#projects-section{% endif %}" class="nav-link"><span>программы</span></a></li>
						<li class="nav-item"><a href="{% if request.path != "/" %}{% url "main:index" %}{% else %}#contact-section{% endif %}" class="nav-link"><span>оставить заявку</span></a></li>
						<li class="nav-item"><a href="{% if request.path == "/students/" %}#students{% else %}{% url "main:students" %}{% endif %}" class="nav-link"><span>поступающим</span></a></li>
						{% if not user.is_authenticated %}
						<li class="nav-item"><a href="{% if request.path == "/login/" %}#login{% else %}{% url "users:login" %}{% endif %}" class="nav-link"><span>войти</span></a></li>
						{% endif %}
						
						{% if user.is_authenticated %}
						<li class="nav-item"><a href="{% url "users:logout" %}" class="nav-link"><span>выйти</span></a></li>
						{% endif %}

						{% if is_superuser == True %}
						<li class="nav-item"><a href="{% url "admin:index" %}" class="nav-link"><span>админ</span></a></li>
						{% endif %}
						
						<li class="nav-item">
							<a class="nav-link" href="{% url "main:toggle_theme" %}">
								{% if request.session.theme == 'dark' %}
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-sun-fill" viewBox="0 0 16 16">
									<path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8M8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0m0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13m8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5M3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8m10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0m-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0m9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707M4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708"/>
								</svg>
								{% else %}
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-moon-fill" viewBox="0 0 16 16">
									<path d="M6 .278a.77.77 0 0 1 .08.858 7.2 7.2 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277q.792-.001 1.533-.16a.79.79 0 0 1 .81.316.73.73 0 0 1-.031.893A8.35 8.35 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.75.75 0 0 1 6 .278"/>
								</svg>
								{% endif %}
							</a>
						</li>


						{% comment %} Поиск {% endcomment %}
						{% comment %} <li>         
							  <form action="#" class="search-form">
								<div class="form-group">
								  <span class="icon icon-search"></span>
								  <input type="text" class="form-control" placeholder="Искать..." style="width: 220px;">
								</div>
							  </form>
						</li> {% endcomment %}

						<style> 
						</style>
					
					</ul>
				</div>

			</div>
		</nav>

		{% comment %} Пустая секция {% endcomment %}
		<section class="ftco-section ftco-hireme img margin-top" id="projects-section" style="background: {% if request.session.theme == 'light' %}white{% else %}black{% endif %}; margin-top:-160px;">
		</section>

		{% block section %}
		{% endblock section %}
			
		{% comment %} Подвал {% endcomment %}
		<footer class="ftco-footer ftco-section" style="margin-top:50px;border-top:2px solid {% if request.session.theme == 'light' %}black{% else %}white{% endif %};">
			<div class="container">
				<div class="row mb-5">

					<div class="col-md">
						<div class="ftco-footer-widget mb-4">
						<h2 class="ftco-heading-2">Документы</h2>
						
						<p> <a href="https://dpo.fa.ru/privacy">Политика конфиденциальности</a> </p>
						
						<p> <a href="https://dpo.fa.ru/soglasienaobr">Согласие на обработку персональных данных</a> </p>
						{% comment %} <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
							<li class="ftco-animate"><a href="https://vk.com/officialfaperm"><span class="icon-vk"></span></a></li>
						</ul> {% endcomment %}
						</div>
					</div>

					<div class="col-md">
						<div class="ftco-footer-widget mb-4">
							<h2 class="ftco-heading-2">Адрес</h2>
							<p> <a>614077, Пермский край, г. Пермь, ​б-р Гагарина, д. 50</a> </p>
						</div>
					</div>
					
					<div class="col-md">
						<div class="ftco-footer-widget mb-4">
							<h2 class="ftco-heading-2">Контакты</h2>
							<p> <a>Телефон</a> </p>
							<p> <b><a>+7 (342) 261-82-32</a></b> </p>
							<p> <b><a>Катаева Нина Сергеевна</a></b> </p>
							<p> <a>Электронная почта</a> </p>
							<p> <b><a>nskataeva@fa.ru</a></b> </p>
							
						</div>
					</div>

					<div class="col-md">
						<div class="ftco-footer-widget mb-4">
							<h2 class="ftco-heading-2">Время работы</h2>
							<p> <a>Понедельник-четверг - <b>с 09:00 до 17:30</b>, </p>
							<p> пятница - <b>с 09:00 до 16:15</b>,</a> </p>
							<p> перерыв - с 13:00 до 13:45 </p>
						</div>
					</div>

				</div>
			</div>
		</footer>
		
		<!-- Значок загрузки -->
		<div id="ftco-loader" class="show fullscreen">
			<svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
				<circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/>
			</svg>
		</div>
		
		{% comment %} JavaScripts {% endcomment %}
		<div>
			<script src="{% static 'js/jquery.min.js' %}"></script>
			<script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
			<script src="{% static 'js/popper.min.js' %}"></script>
			<script src="{% static 'js/bootstrap.min.js' %}"></script>
			<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
			<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
			<script src="{% static 'js/jquery.stellar.min.js' %}"></script>
			<script src="{% static 'js/owl.carousel.min.js' %}"></script>
			<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
			<script src="{% static 'js/aos.js' %}"></script>
			<script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
			<script src="{% static 'js/scrollax.min.js' %}"></script>
			<script src="{% static 'js/modal_window.js' %}"></script>
			
			<script src="{% static 'js/main.js' %}"></script>
			{% comment %} <script src="{% static 'js/anime.min.js' %}"></script> {% endcomment %}

			{% block js %}
			
			{% endblock js %}

		</div>
		
	</body>

</html>