app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from app import settings




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('users.urls', namespace='users')),
]


admin.site.site_header = "Панель администратора"
admin.site.site_title = "Администрирование"
admin.site.index_title = ""

# if settings.DEBUG:
#     urlpatterns += [
#     path("__debug__/", include("debug_toolbar.urls")),
# ]

# if settings.DEBUG:
#         urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)    

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('toggle_theme/', views.toggle_theme, name='toggle_theme'),
    path('curse/<slug:curse_slug>/', views.curse_cart, name='curse_cart'),
    path('students/', views.students, name='students'),
    path('get_file/', views.export_to_csv, name='get_file'),
    path('news/<slug:news_slug>', views.news, name='news'),
]

main/models.py
from django.db import models
from django.utils.safestring import mark_safe

from users.models import User
import random

class Settings(models.Model):
    theme = models.CharField(max_length=5, default='light') 
    
class Curses(models.Model): 
    name = models.CharField(max_length=256, unique=True, verbose_name='Название')
    edu_form = models.CharField(max_length=15, verbose_name='Форма обучения')
    slug = models.SlugField(max_length=256, unique=True, blank=True, null=True, verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание', default='Описание программы еще не добавлено')
    sertificate = models.URLField(blank=True, null=True, verbose_name='Сертификат об окончании (URL)')
    structure = models.TextField(blank=True, null=True, verbose_name='Структура программы', default='Структура программы еще не добавлена')
    hours = models.IntegerField(blank=True, null=True, verbose_name='Количество часов',)
    image = models.ImageField(upload_to='curse_image', blank=True, null=True, verbose_name='Изображение')
    paid_or_free = models.CharField(max_length=2, blank=True, null=True, default='б', verbose_name='Бюджет/Внебюджет (б/вб)')
    price = models.IntegerField(blank=True, null=True, verbose_name='Цена, в руб.', default=random.randint(100000,200000))

    class Meta:
        db_table = 'curse'
        verbose_name = 'Направление'
        verbose_name_plural = 'Направления'

    def __str__(self):
        return self.name

    def get_image(self):
        if not self.image:
            return '/static/images/no_photo.png'
        return self.image.url

    def image_tag(self):
        return mark_safe('<img src="%s" width=150px height=150px />' % self.get_image())

    image_tag.short_description = 'Фото'

class Disciplines(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    curse = models.ForeignKey(to=Curses, on_delete=models.CASCADE, verbose_name='Направление')

    class Meta:
        db_table = 'discipline'
        verbose_name = 'Дисциплина'
        verbose_name_plural = 'Дисциплины'

    def __str__(self):
        return self.name

class Students(models.Model):
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    surname = models.CharField(max_length=150, blank=True, null=True, verbose_name='Отчество')
    birth_date = models.DateField(max_length=10, blank=True, null=True, verbose_name='Дата рождения')
    curse = models.ForeignKey(to=Curses, on_delete=models.CASCADE, verbose_name='Направление', blank=True, null=True,)
    email = models.EmailField(blank=True, null=True,verbose_name='Email')
    phone = models.CharField(blank=True, null=True,verbose_name='Номер телефона')
    description = models.TextField(verbose_name='Примечания', null=True, blank=True)
    curse_is_paid = models.BooleanField(verbose_name='Оплачено?', default=False)


    class Meta:
        db_table = 'student'
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'

class Lecturers(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    surname = models.CharField(max_length=150, verbose_name='Отчество')
    education = models.CharField(max_length=150, unique=True, verbose_name='Образование', null=True, blank=True)
    description = models.TextField(verbose_name='Описание', null=True, blank=True)
    discipline = models.ForeignKey(to=Disciplines, on_delete=models.CASCADE, verbose_name='Дисциплина')
    image = models.ImageField(upload_to='lecturer_image', blank=True, null=True, verbose_name='Изображение')
    curse = models.ForeignKey(to=Curses, on_delete=models.CASCADE, verbose_name='Направление', null=True, blank=True)

    
    class Meta:
        db_table = 'lecturer'
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'

class Documents(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    url = models.URLField(max_length=150, unique=True, verbose_name='Ссылка на документ')
    curse = models.ForeignKey(to=Curses, on_delete=models.CASCADE, verbose_name='Направление')

    class Meta:
        db_table = 'document'
        verbose_name = 'Документ'
        verbose_name_plural = 'Добавить документы'

class News(models.Model):
    title = models.CharField(max_length=150, verbose_name='Заголовок', default='Заголовок интересной новости')
    subtitle = models.TextField(verbose_name='Подзаголовок', default='Подзаголовок интересной новости')
    date = models.DateField(auto_now_add=True, verbose_name='Дата публикации')
    text = models.TextField(verbose_name='Текст новости', blank=True, null=True)
    image = models.ImageField(upload_to='news_image', blank=True, null=True, verbose_name='Изображение')
    slug = models.SlugField(max_length=256, unique=True, blank=True, null=True, verbose_name='URL')


    class Meta:
        db_table = 'news'
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

    def get_image(self):
        if not self.image:
            return '/static/images/no_photo.png'
        return self.image.url

    def image_tag(self):
        return mark_safe('<img src="%s" width=150px height=150px />' % self.get_image())

    image_tag.short_description = 'Фото'

class NewsTag(models.Model):
    tag = models.CharField(max_length=50, verbose_name='Тег')
    new = models.ForeignKey(to=News, on_delete=models.CASCADE, verbose_name='Новость', blank=True, null=True,)

    class Meta:
        verbose_name = 'Тег'
        verbose_name_plural = 'Теги'
    

main/forms.py
from django import forms


from main.models import Students, Settings


class RequestEducationForm(forms.ModelForm):
    class Meta:
        model = Students
        fields = [
            'first_name',
            'last_name',
            'surname',
            'birth_date',
            'email',
            'phone',
            'curse',
        ]

class SettingsForm(forms.ModelForm):
    class Meta:
        model = Settings
        fields = [
            'theme',
        ]
    

main/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse


from main.forms import RequestEducationForm
from main.models import Curses, Documents, News, NewsTag, Students

import csv
import random as r
from datetime import datetime 

def toggle_theme(request):
    current_theme = request.session.get('theme','light')

    if current_theme == 'light':
        request.session['theme'] = 'dark'
    else:
        request.session['theme'] = 'light'

    return redirect(request.META.get('HTTP_REFERER','/'))

def index(request):
    
    theme = request.GET.get('action')
    if theme == None:
        theme = 'light'
        
    news = News.objects.all().order_by('-date')

    if len(News.objects.all()) > 3:
        news = News.objects.all().order_by('-date')[:3]


    curses = Curses.objects.all()
    len_curses_is_even = False
    len_curses = len(Curses.objects.all())
    if len_curses%2 == 0:
        len_curses_is_even = True

    last_index = len(Curses.objects.all())-1
    last_curse = Curses.objects.all()[last_index]

    year = datetime.now().year - 1930
    
    if request.method == 'POST':
        form = RequestEducationForm(request.POST)
        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('main:students'))      
    else:
        form = RequestEducationForm()
        

    context = {
        'title': 'ДПО - Главная',
        'content': "",
        'is_superuser': request.user.is_superuser,
        'curses': curses,
        'form': form,
        'last_curse': last_curse,
        'len_curses_is_even': len_curses_is_even,
        'len_curses': len_curses,
        'news':news,
        'year':year,
        'theme':theme,

    }

    
    

    return render(request, 'main/index.html', context)

def curse_cart(request, curse_slug):

    curse = Curses.objects.get(slug=curse_slug)
    documents = Documents.objects.all()

    context = {
        'title': 'ДПО - Курсы',
        'content': "",
        'curse': curse,
        'documents': documents,
    }
    


    return render(request, 'main/curse_cart.html', context)

def students(request):

    students = Students.objects.all()
    
    context = {
        'title': 'ДПО - Поступающим',
        'content': "",
        'students': students,
    }
    
    return render(request, 'main/students_curses_list.html', context)

def news(request, news_slug):

    news = News.objects.get(slug=news_slug)
    recent_news = News.objects.exclude(slug=news_slug)
    if len(recent_news) > 3:
        recent_news = News.objects.exclude(slug=news_slug)[:3]

    all_news_tags = NewsTag.objects.all()
    news_tags = NewsTag.objects.filter(new_id=news.id)
    
    
    context = {
        'title': 'ДПО - Новости',
        'content': "",
        'news': news,
        'recent_news': recent_news,
        'news_tags': news_tags,
        'all_news_tags': all_news_tags,
    }
    


    return render(request, 'main/single.html', context)

def export_to_csv(request):
    
    # Создаем HTTP-ответ с типом содержимого 'text/csv'
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="students.csv"'

    # Создаем объект writer для записи в CSV
    writer = csv.writer(response)

    # Записываем заголовки столбцов
    writer.writerow([
        'Фамилия',
        'Имя',
        'Отчество',
        'Дата рождения',
        'Программа обучения',
        '№ заявления',
        'Бюджет/Внебюджет',
        'Форма обучения',
        'Эл. почта',
        'Телефон',
        'Примечания',
        'Оплачен курс?'
    ]) 

    # Получаем данные из модели
    queryset = Students.objects.all()

    # Записываем данные в CSV
    for obj in queryset:
        numb_statement = 'К-0000' + str(obj.id) 
        writer.writerow([
            obj.last_name,
            obj.first_name,
            obj.surname,
            obj.birth_date,
            obj.curse,
            numb_statement,
            obj.curse.paid_or_free,
            obj.curse.edu_form,
            obj.email,
            obj.phone,
            obj.description,
            obj.curse_is_paid,
        ]) 

    return response

main/templates/main/curse_cart.html
{% extends "base.html" %}
{% load static %}

{% block section %}

    {% comment %} Инфо о программе {% endcomment %}
    <section class="ftco-section contact-section ftco-no-pb" id="projects-section" style="padding-top:5px">
        
        <div class="container">  

            {% comment %} Название программы {% endcomment %}
            <div class="row justify-content-center mb-5 pb-3" style="margin-bottom:24px;">
                <div class="col-md-12 heading-section text-center ftco-animate">
                    <h2 class="mb-4">{{ curse.name }}</h2>
                </div>
            </div>

            {% comment %} Фото программы {% endcomment %}
            <div class="col-md-12 heading-section text-center ftco-animate">
                <p>
                    <img src="{% if curse.image %}{{ curse.image.url }}{% else %}{% static "images/form-photo.jpg" %}{% endif %}" style="height:60%;width:80%; border-radius:20px">
                </p>
            </div>

            {% comment %} Кнопка записаться {% endcomment %}
            <div class="col-md-12 heading-section text-center ftco-animate" style="margin-bottom:100px">
                <p>
                    <a href="" class="btn btn-primary py-3 px-4" style="width:80%; line-height:100%;font-size:16px;">Записаться сейчас</a>
                </p>
            </div>

            {% comment %} Информация о программе {% endcomment %}
            <div class="row no-gutters block-9 ftco-animate">
                
                <div class="col-md-8">
                    <h1>Описание</h1>
                    <li class="nav-item">
                        {{ curse.description }}
                    </li>
                </div>
                
            
                <div class="col-md-8" style="margin-bottom:20px;margin-top:20px;">
                    <h1>Форма обучения</h1>
                    <ul class="">
                        <li class="nav-item">{{ curse.edu_form }}</li>
                    </ul>
                </div>
            
                <div class="col-md-8" style="margin-bottom:20px;margin-top:20px;">
                    <h1>Документ по окончании</h1>
                    <a href="{{ curse.sertificate }}">Удостоверение о повышении квалификации</a>
                </div>

                <div class="col-md-8" style="margin-bottom:20px;margin-top:20px;">
                    <h1>Структура программы</h1>
                    <p>
                        {{ curse.structure }}
                    </p>
                    {% comment %} <ol>
                        <li class="nav-item">Основные функции, режимы и правила работы с программой </li>
                        <li class="nav-item">Базовые операции по учету кадрами в организации.</li>
                        <li class="nav-item">Расчет зарплаты в организации, отчеты и унифицированные формы.</li>
                        <li class="nav-item">Основные функции, режимы и правила работы с программой.</li>
                        <li class="nav-item">Решение комплекса задач бухгалтерской службы.</li>
                    </ol> {% endcomment %}
                </div>
            

            
                <div class="col-md-8" style="margin-bottom:20px;margin-top:20px;">
                    <h1>Документы</h1>
                    <p>
                        <div class="row">
                            {% if not document.url %}
                                <div class="col-md-auto">
                                    <p>
                                        Документы еще не добавлены
                                    </p>
                                </div>
                            {% endif %}

                            {% for document in documents %}
                                <div class="col-md-auto">
                                    <a href="{{ document.url }}">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="32" height="32" fill="none" stroke="currentcolor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2">
                                            <path d="M28 22 L28 30 4 30 4 22 M16 4 L16 24 M8 16 L16 24 24 16" />
                                        </svg>
                                    </a>
                                </div>

                                <div class="col-md-auto">
                                    <a href="{{ document.url }}">{{ document.name }}</a>
                                </div>
                            {% endfor %}

                        </div>
                    </p>
                </div>
                    
                
                    
            </div>

        </div>

    </section>

    {% if lecturer.first_name %}
        {% comment %} Карточки преподователей {% endcomment %}
        <section class="ftco-about img ftco-section ftco-no-pb" id="projects-section" style="padding-top:10px"> 	
            <div class="container">
                <h1 class="mb-4">Преподаватели</h1>
            </div>

            {% comment %} Карточка преподавателя {% endcomment %}
            <div class="container" style="margin-top:30px">
                {% comment %} <h1 class="mb-4">Преподаватели</h1> {% endcomment %}
                <div class="row d-flex">
                    <div class="col-md-6 col-lg-5 d-flex">
                        <div class="img-about img d-flex align-items-stretch">
                            <div class="overlay"></div>
                                <div class="img d-flex align-self-stretch align-items-center" style="background-image:url({% if lecturer.image %}{{ lecturer.image }}{% else %}{% static 'images/person-default.png' %}{% endif %});border:3px solid white;height:445px">
                            </div>
                        </div>
                    </div>

                    <div class="col-md-6 col-lg-7 pl-lg-5 pb-5">
                        <div class="row justify-content-start pb-3">
                            <div class="col-md-12 heading-section ftco-animate">
                                
                                <h3 class="mb-4">{{ lecturer.first_name }} {{ lecturer.last_name }} {{ lecturer.surname }}</h3>
                                <p>{{ lucturer.description }}</p>
                                
                                <ul class="about-info mt-4 px-md-0 px-2">
                                    <li class="d-flex"><span>{{ lecturer.education }}</span></li>
                                </ul>

                            </div>
                        </div>

                    </div>
                </div>

            </div>

        
        </section>
    {% endif %}

{% endblock section %}

main/templates/main/single.html
{% extends "base.html" %}
{% load static %}

{% block css %}
{% endblock css %}

{% block section %}
  <section class="hero-wrap js-fullheight" style="background-image: url('{% static 'images/bg_1.jpg' %}');" data-stellar-background-ratio="0.5">  
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
        <div class="col-md-12 ftco-animate pb-5 mb-3 text-center">
          <h4 class="mb-3 bread">{{ news.title|truncatechars:30 }}</h3>
          <p class="breadcrumbs"><span class="mr-2"><a href="{% url "main:index" %}">ДПО <i class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="">Новости<i class="ion-ios-arrow-forward"></i></a></span> <span>{{ news.title }} <i class="ion-ios-arrow-forward"></i></span></p>
        </div>
      </div>
    </div>
  </section>

  <section class="ftco-section">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 ftco-animate">
          <h2 class="mb-3 mt-5">Невероятные новости!</h2>

          <p>
            Речь идет о планете KIC-1412b, расположенной в зоне обитаемости звезды, похожей на наше Солнце.
             С помощью новейшего телескопа JWST (James Webb Space Telescope) астрономы зафиксировали не только наличие воды и кислорода в атмосфере,
              но и странные структуры на поверхности, напоминающие искусственные сооружения.
          </p>

          <p>
            Более того, в атмосфере планеты обнаружены следы химических соединений, которые могут быть побочными продуктами технологической деятельности.
             Ученые предполагают, что это может указывать на существование развитой цивилизации. "Это открытие меняет всё, что мы знали о Вселенной", 
             — заявил доктор Эмили Картер, ведущий исследователь проекта.
          </p>

          <p>
            <img src="{% static 'images/default_person.png' %}" alt="" class="img-fluid">
          </p>
        
          
          <div class="tag-widget post-tag-container mb-5 mt-5">
            <div class="tagcloud">
            {% for tags in news_tags %}
              <a href="#" class="tag-cloud-link">{{ tags.tag }}</a>  
            {% endfor %}
            </div>
          </div>
          
          <div class="about-author d-flex p-4 bg-dark">
            <div class="bio mr-5">
              <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder" class="img-fluid mb-4">
            </div>
            <div class="desc">
              <h3>George Washington</h3>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur similique, inventore eos fugit cupiditate numquam!</p>
            </div>
          </div>


        </div> <!-- .col-md-8 -->
        <div class="col-lg-4 sidebar ftco-animate">



          {% comment %} <div class="sidebar-box ftco-animate">
            <h3 class="heading-sidebar">Categories</h3>
            <ul class="categories">
              <li><a href="#">Interior Design <span>(12)</span></a></li>
              <li><a href="#">Exterior Design <span>(22)</span></a></li>
              <li><a href="#">Industrial Design <span>(37)</span></a></li>
              <li><a href="#">Landscape Design <span>(42)</span></a></li>
            </ul>
          </div> {% endcomment %}

          <div class="sidebar-box ftco-animate">
            <h3 class="heading-sidebar">Недавние</h3>
            {% for new in recent_news %}
              <div class="block-21 mb-4 d-flex">
                <a class="blog-img mr-4" style="background-image: url('{% if new.image %}{{ new.image.url }}{% else %}{% static 'images/person-default.png' %}{% endif %}');"></a>
                <div class="text">
                  <h3 class="heading"><a href="{% url "main:news" new.slug %}">{{ new.title }}</a></h3>
                  <div class="meta">
                    <div><a href="#"><span class="icon-calendar"></span> {{ new.date }}</a></div>
                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                    {% comment %} <div><a href="#"><span class="icon-chat"></span> 0</a></div> {% endcomment %}
                  </div>
                </div>
              </div>
            {% endfor %}
            

          </div>

          <div class="sidebar-box ftco-animate">
            <h3 class="heading-sidebar">Все теги</h3>
            <div class="tagcloud">
              {% for tags in all_news_tags %}
                <a href="#" class="tag-cloud-link">{{ tags.tag }}</a>
              {% endfor %}

            </div>
          </div>


        </div>

      </div>
    </div>
  </section> 

{% endblock section %}
    
{% block js %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>

  <script src="{% static 'js/main.js' %}"></script>
{% endblock js %}

main/templates/main/students_curses_list.html
{% extends "base.html" %}
{% load static %}

{% block css %}
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
        }
        th, td {
            border: 3px solid #999999;
            padding: 8px;
            text-align: justify;
        }

        
        [data-tooltip] {
            position: relative; /* Относительное позиционирование */ 
        }
        [data-tooltip]::after {
            content: attr(data-tooltip); /* Выводим текст */
            position: absolute; /* Абсолютное позиционирование */
            
            left: 0; top: 0; /* Положение подсказки */
            
            color: #fff; /* Цвет текста */
            padding: 0.5em; /* Поля вокруг текста */
            
            pointer-events: none; /* Подсказка */
            opacity: 0; /* Подсказка невидима */
            transition: 0.5s; /* Время появления подсказки */
        } 
        [data-tooltip]:hover::after {
            opacity: 1; /* Показываем подсказку */
            top: 2em; /* Положение подсказки */
        }
        
    </style>
{% endblock css %}

{% block section %}
    <section class="ftco-section ftco-animate" id="students">
        <div class="container">

            <div class="row justify-content-center pb-5">
                <div class="col-md-12 heading-section text-center ftco-animate">
                    <h2 class="mb-4" style="text-align: left;">Список поступивших</h2>
                </div>
            </div>

            {% comment %} Таблица студентов {% endcomment %}
            <table>
                <thead>
                    <tr>
                        <th>№</th>
                        <th>ФИО студента</th>
                        <th>Направление</th>
                        <th>Дата рождения</th>
                        <th>№ заявления</th>
                        <th>Бюджет/Внебюджет</th>
                        <th>Форма обучения</th>
                        <th>Примечания</th>
                        
                    </tr>
                </thead>

                <tbody>

                    {% for s in students %}
                        {% if s.curse_is_paid == True %}
                        <tr>
                            <td>{{ s.id }}</td>
                            <td>{{ s.last_name }} {{ s.first_name }} {{ s.surname }}</td>
                            <td>{% if s.curse %}{{ s.curse }}{% else %}{% endif %} </td>
                            <td>{{ s.birth_date }}</td>
                            <td style="text-align: center;">К-0000{{ s.id }}</td>
                            <td style="text-align: center;">{{ s.curse.paid_or_free }}</td>
                            <td style="text-align: center;">{{ s.curse.edu_form }}</td>
                            <td>{% if s.description %}{{ s.description }}{% else %}{% endif %}</td>
                        </tr>
                        {% endif %}
                    {% endfor %}

                </tbody>
            </table>

            {% comment %} Скачать таблицу {% endcomment %}
            <div class="col-md-8">
                <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5" data-tooltip='Скачать в CSV'>
                    <li class="ftco-animate">
                        <a href="{% url "main:get_file" %}">
                            <span class="icon-table"></span>
                        </a>
                    </li>
				</ul>
            </div>

        </div>
    </section>
{% endblock section %}